### ISSUE TITLE
The e-mail address validator is wrong

### ISSUE THREAD

**Issue by Hixie** [seamonkeysocial/twitarr#11]
We use this to validate e-mail addresses:

```ruby
  validates :email, format: { with: /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i, message: 'address is not valid.' }
```

This is wrong. It considers e-mail addresses such as `ian@rooves.house` to be invalid, but that's a valid e-mail address. It also considers `a=b@example.com` to be invalid, but that's a valid e-mail address.

Also, it allows data before and after the e-mail address, for example it considers `The value <foo@example.com> is not my e-mail address` to be a valid e-mail address.

The following is the regular expression that the HTML spec recommends to validate e-mail addresses:

```perl
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
```

**Comment by Tratcher** [comment]
The email address is never used, why bother validating it?

**Comment by hendusoone** [comment]
There's not much point in requiring the e-mail address during registration, other than having it on file in case we want to send out some sort of notification before putting the twitarr archives online post-cruise (which is something we haven't done in a while). We don't confirm the e-mail address for new sign-ups. It _could_ be removed from registration, but I'd rather keep it in.

I do agree that the current regex needs to be fixed or removed. But before changes are made, a consensus on which one to use (or to remove) should be made, and we should use the same one everywhere (if possible).

I do like @grundoon 's suggestion. I can't really pose an alternative, since I'm mostly a .NET guy who does email validation using System.Net.Mail.MailAddress.

**Comment by Tratcher** [comment]
I had to update System.Net.Mail.MailAddress a while back. Validation is a very deep rat hole, especially now that unicode email addresses are going live. Best to keep it a simple "anychars@anychars".

**Comment by grundoon** [comment]
Is it my lack of regex parsing fu, or does not even the W3C one allow either of my original totally valid addresses... grundoon@[8.8.8.8] or bang path formats?

**Comment by Hixie** [comment]
I don't believe IPv6 addresses or bang path formats are allowed by the specs these days.

The HTML spec regexp doesn't attempt to support IDN e-mail addresses because the HTML type=email form field is supposed to convert them to punycode.

If we don't really care about the exact syntax, we might want to just allow anything, or anything with a single "@", or something. I don't really mind what we allow, I just noticed that what we require now is not correct. :-) I'll make the client I'm writing locally test against whatever the server tests for.

**Comment by hendricksond** [comment]
Ruby has a built-in email address regexp, URI::MailTo::EMAIL_REGEXP, which is an implementation of the one recommended by the HTML spec. I'm going to switch it to use that - while not perfect, it's better than what we have now.

It's also likely that e-mail address will be removed from registration in the near future. If it is removed from registration, it will be kept on the user profile for anyone who wants to publicize it.
