### ISSUE TITLE
Links in tweets don't work

### ISSUE THREAD

**Issue by rgorski** [seamonkeysocial/twitarr#180]
Links in tweets don't work. Discovered when clicking a mention and expecting to get the user's profile, but instead got the tweet itself or the thread it was a part of. Added a link to a new tweet and it just didn't work.

Google Chrome Version 71.0.3578.98 (Official Build) (64-bit) on macOS Mojave 10.14.3

**Comment by hendricksond** [comment]
The solution for this issue is to remove the clickability of the full tweet. So, clicking a tweet will no longer take you to the thread. Now, you will need to click the tweet's timestamp to load the thread. This may actually be a little bit more user-friendly - fewer accidental thread load clicks. But, it is a little bit less discoverable.
