### ISSUE TITLE
/api/v2/seamail_threads?after=... should include changed threads

### ISSUE THREAD

**Issue by Hixie** [seamonkeysocial/twitarr#309]
Threads can change -- specifically, the unread status of a message in a thread can change -- in a way that won't be exposed by `/api/v2/seamail_threads?after=...`. This means that e.g. if you receive a message but open it on another device, a client using this API won't be informed that it should mark the thread as read. The same happens if a client hits this endpoint, learns about a new message, then opens the thread using `/api/v2/seamail/$id`, which marks the message as read, then uses `/api/v2/seamail_threads?after=...` again, because the first hit to `/api/v2/seamail/$id` considers the thread as unread so you never get data from the server saying it's read (even though obviously it is).

**Comment by Hixie** [comment]
I'm pretty sure this is the cause of https://github.com/seamonkeysocial/rainbowmonkey/issues/239 which we had reported last year.

**Comment by hendricksond** [comment]
Yeah, after looking at this a bit more (and discussing in chat), the behavior is by design. When the `after` parameter is used, it only considers the timestamp of the thread - that is, when the most recent message was posted. Changing the thread's read status for a user does not impact the thread's timestamp. The solution is to call `seamail_threads` without the `after` parameter.
